### ISSUE TITLE
Swap out MaxCDN logo for StickerMule in sopnsers block

### ISSUE THREAD

**Issue by kpearson** [fullstackla/fullstackla.github.io#35]
We should host the image/SVG asset. (Include it in Fullstack site assets.

Currently, MaxCDN is hot linked from the MaxCDN site. This is not a good practice.

**Comment by jaimemendozadev** [comment]
Placed Sticker Mule asset in img/logos folder with other img assets. 

The Sticker Mule logo is an SVG with transparent white lettering. We might need to change the background color of the sponsors block and change the BG-Color order of the other blocks.

Please note the SM logo white lettering still looks difficult to read with a bg-light-gray color.
